[workspace]
authors = ["Phil9S <philip.smith@cruk.cam.ac.uk>"]
channels = ["conda-forge", "bioconda"]
name = "swgs-abscn"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = "4.3.3.*"
snakemake = "*"
snakemake-executor-plugin-slurm = "*"
python = "*"
pandas = "*"
"ruamel.yaml" = "*"
samtools = "*"
bioconductor-biobase = "*"
bioconductor-biocgenerics = "*"
r-tidyverse = "*"
r-matrixstats = "*"
r-plyr = "*"
bioconductor-qdnaseq = "*"
"bioconductor-qdnaseq.hg19" = "*"
r-remotes = "*"
r-ranger = "*"
r-parsnip = "*"

