---
# Sample sheet
samplesheet: "sample_sheet.tsv"

# Output location
out_dir: "/mnt/scratcha/fmlab/smith10/swgs_test/"

# Bin sizes
# By default any in [1,5,15,30,50,100,500,1000]
bins:
- 30
project_name: "nm_test"

# Pipeline parameters
af_cutoff: 0.15

# Set seed for CBS - TRUE or FALSE
# default TRUE
use_seed: "TRUE"
seed_val: "9999"

# fitler underpowered solutions - TRUE or FALSE
# Default TRUE
filter_underpowered: "TRUE"

# Not implemented
#custom_bin: false
#custom_bin_folder: "/custom_bin_data/"
