---
# Sample sheet
samplesheet: sample_sheet.tsv

# Output location
out_dir: results/

# Bin sizes
# By default any in [1,5,15,30,50,100,500,1000]
# Add new line for additional bin sizes
bins:
- 30
#- 100 

# Set project dir name
project_name: nm_test

# Pipeline parameters
af_cutoff: 0.15

# Set seed for CBS - TRUE or FALSE
# default TRUE
use_seed: "TRUE"
seed_val: "9999"

# fitler underpowered solutions - TRUE or FALSE
# Default TRUE
filter_underpowered: "TRUE"

# ploidy range
# Default min = 1.6 | max = 8
ploidy_min: 1.6
ploidy_max: 8.0

# purity range (1 >= max > min >= 0)
# Default min = 0.15 | max = 1.00
purity_min: 0.15
purity_max: 1.0

# Homozygous loss filter - TRUE or FALSE
# Default "TRUE"
filter_homozygous: "TRUE"
# Threshold basepairs lost
# Default 10000000 / 10Mbase
homozygous_prop: 10000000
# Absolute CN homozygous loss threshold
# Default 0.4
homozygous_threshold: 0.4

# container url for swgs-absolutecn
image_base_url: docker://phil9s/

# genome build - either hg19 or hg38
genome: "hg19"

# Not implemented
#custom_bin: false
#custom_bin_folder: "/custom_bin_data/"
