---
# Sample sheet
samplesheet: "sample_sheet.tsv"

# Output location
out_dir: "/mnt/scratcha/fmlab/smith10/"

# Bin sizes
# By default any in [1,5,15,30,50,100,500,1000]
bins:
- 100
project_name: "britroc"

# Pipeline parameters
af_cutoff: 0.15

# Not implemented
#custom_bin: false
#custom_bin_folder: "/custom_bin_data/"
