$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  out_dir:
    type: string
  bins:
    type: array
  project_name:
    type: string
  af_cutoff:
    type: number
    min: 0
    max: 1.0

# entries that have to be in the config file for successful validation
required:
  - samplesheet
  - out_dir
  - bins
  - project_name

