rule gridsearch_fitting:
    input:
        rds=expand(OUT_DIR+"sWGS_fitting/{{project}}_{{bin}}kb/absolute_PRE_down_sampling/relative_cn_rds/{{project}}_{{sample}}_{{bin}}kb_relSmoothedCN.rds")
    output:
        fit=OUT_DIR+"sWGS_fitting/{project}_{bin}kb/absolute_PRE_down_sampling/{project}_{sample}_fit_QC_predownsample.tsv"
    singularity:
        image_base_url+"swgs-absolutecn:latest"
    params:
        bin="{bin}",
        outdir=OUT_DIR,
        project="{project}",
        meta=config["samplesheet"],
        ploidy_min=config["ploidy_min"],
        ploidy_max=config["ploidy_max"],
        purity_min=config["purity_min"],
        purity_max=config["purity_max"],
        homozygous_threshold=config["homozygous_threshold"],
        genome=config["genome"],
        sample="{sample}",
        af_cutoff=config["af_cutoff"],
        filter_underpowered=config["filter_underpowered"],
        filter_homozygous=config["filter_homozygous"],
        homozygous_prop=config["homozygous_prop"]
    script:
        "../scripts/gridsearch.R"
